from dotenv import load_dotenv
load_dotenv()  # Load variables from .env file

from flask import Flask, request, jsonify, send_from_directory, session
from flask_cors import CORS
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from travel_agent import run_multi_agent
from models import db, User, Trip, ContactQuery
from io import BytesIO
from email.message import EmailMessage
import smtplib
import os
import re
import json
from datetime import datetime

app = Flask(__name__, static_folder="../frontend")
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY', 'dev_secret_key_change_in_prod')
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///users.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SESSION_COOKIE_SAMESITE'] = 'Lax'
app.config['SESSION_COOKIE_SECURE'] = False # True requires HTTPS

CORS(app, supports_credentials=True)

db.init_app(app)
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'

@login_manager.unauthorized_handler
def unauthorized():
    return jsonify({'error': 'Unauthorized', 'message': 'Please log in to access this resource'}), 401

with app.app_context():
    db.create_all()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# Professional PDF generation function (kept as is)
def generate_pdf(summary, agent_outputs):
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem, 
                                    Table, TableStyle, PageBreak, KeepTogether, Image)
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY, TA_RIGHT
    from reportlab.lib.colors import HexColor, black, white, Color
    from reportlab.lib.units import inch
    from reportlab.pdfgen import canvas
    import re
    from datetime import datetime
    
    buffer = BytesIO()

    # --- Custom Canvas for Header/Footer ---
    class TripTacticxTemplate(canvas.Canvas):
        def __init__(self, *args, **kwargs):
            canvas.Canvas.__init__(self, *args, **kwargs)
            self.pagesize = letter

        def showPage(self):
            self.draw_header_footer()
            canvas.Canvas.showPage(self)

        def draw_header_footer(self):
            # Footer
            self.saveState()
            self.setFont("Helvetica", 9)
            self.setFillColor(HexColor("#94a3b8"))
            self.drawString(1 * inch, 0.75 * inch, "Generated by TripTacticx AI")
            self.drawRightString(7.5 * inch, 0.75 * inch, f"Page {self._pageNumber}")
            self.setStrokeColor(HexColor("#e2e8f0"))
            self.line(1 * inch, 0.9 * inch, 7.5 * inch, 0.9 * inch)
            self.restoreState()
    
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)
    
    styles = getSampleStyleSheet()
    
    # --- Professional Styles ---
    # Brand Colors: Cyan (#00e5ff) -> PDF safe dark cyan / blue
    brand_blue = HexColor("#0066cc")
    brand_dark = HexColor("#0f172a")
    brand_accent = HexColor("#00e5ff")

    styles.add(ParagraphStyle(
        'CoverTitle',
        parent=styles['Title'],
        alignment=TA_CENTER,
        fontSize=42,
        leading=50,
        spaceAfter=20,
        textColor=brand_dark,
        fontName='Helvetica-Bold'
    ))
    
    styles.add(ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        alignment=TA_CENTER,
        fontSize=18,
        leading=24,
        textColor=HexColor("#64748b"),
        fontName='Helvetica'
    ))

    styles.add(ParagraphStyle(
        'CoverFooter',
        parent=styles['Normal'],
        alignment=TA_CENTER,
        fontSize=12,
        textColor=HexColor("#94a3b8"),
        fontName='Helvetica',
        spaceBefore=200
    ))
    
    styles.add(ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=22,
        leading=28,
        spaceBefore=30,
        spaceAfter=15,
        textColor=brand_blue,
        fontName='Helvetica-Bold',
        borderPadding=(0, 0, 10, 0),
        borderWidth=0,
        borderColor=white
    ))
    
    styles.add(ParagraphStyle(
        'SubSectionHeader',
        parent=styles['Heading3'],
        fontSize=14,
        leading=22,
        spaceBefore=16,
        spaceAfter=8,
        textColor=brand_dark,
        fontName='Helvetica-Bold'
    ))
    
    styles.add(ParagraphStyle(
        'CustomBodyText',
        parent=styles['Normal'],
        fontSize=11,
        leading=18, # Increased leading
        spaceAfter=12,
        textColor=HexColor("#334155"),
        alignment=TA_LEFT,
        fontName='Helvetica'
    ))

    styles.add(ParagraphStyle(
        'Highlight',
        parent=styles['CustomBodyText'],
        textColor=brand_blue,
        fontName='Helvetica-Bold'
    ))

    elements = []
    
    # --- COVER PAGE ---
    # Attempt to extract destination from summary or outputs if possible
    destination = "Your Dream Destination"
    # Basic heuristic to find destination in the output key or summary
    # For now, generic title
    
    elements.append(Spacer(1, 2 * inch))
    elements.append(Paragraph("TRIP TACTICX", 
                             ParagraphStyle('Logo', parent=styles['Normal'], fontSize=16, alignment=TA_CENTER, textColor=brand_blue, fontName='Helvetica-Bold', spaceAfter=20)))
    
    elements.append(Paragraph("TRAVEL ITINERARY", styles['CoverTitle']))
    elements.append(Paragraph("Curated exclusively for you", styles['CoverSubtitle']))
    elements.append(Paragraph(datetime.now().strftime("%B %d, %Y"), styles['CoverSubtitle']))
    
    elements.append(Spacer(1, 3 * inch))
    elements.append(Paragraph("Explore • Experience • Enjoy", styles['CoverFooter']))
    elements.append(PageBreak())
    
    # --- CONTENT ---

    section_map = {
        "Booking Suggestions": "✈️ Flights & Logistics",
        "Stay Options": "🏨 Accommodation",
        "Experiences": "🎨 Experiences & Activities",
        "Local Food & Dining": "🍽️ Culinary Delights",
        "Travel Logistics": "🚗 Local Transport",
        "Budget Planning": "💰 Estimated Budget"
    }

    def clean_text(text):
         # Replace formatting markers
         text = text.replace('**', '')
         text = text.replace('###', '')
         text = text.replace('##', '')
         return text.strip()

    for key, content in agent_outputs.items():
        title = section_map.get(key, key)
        
        # Section Header with line
        elements.append(Paragraph(title, styles['SectionHeader']))
        
        # Parse content
        # Split by double newlines for paragraphs
        parts = content.split('\n\n')
        
        for part in parts:
            part = part.strip()
            if not part: continue
            
            # Subheaders (Day X, Option X, etc)
            if part.startswith('Day') or part.startswith('Option') or part.startswith('**'):
                clean = clean_text(part)
                elements.append(Paragraph(clean, styles['SubSectionHeader']))
            
            # List items
            elif part.strip().startswith('-') or part.strip().startswith('*'):
                items = []
                lines = part.split('\n')
                for line in lines:
                    line = line.strip()
                    if line.startswith('-') or line.startswith('*'):
                       txt = clean_text(line[1:])
                       items.append(ListItem(Paragraph(txt, styles['CustomBodyText'])))
                if items:
                    elements.append(ListFlowable(items, bulletType='bullet', start='circle', leftIndent=20))
            
            # Tables (rough detection for budget)
            elif '|' in part and len(part.split('\n')) > 2:
                 # Attempt simpler parsing or just render as preformatted-ish
                 # For safety/speed, render as text but with monospace font if needed
                 # Or just render as BodyText for now to avoid breaking PDF
                 elements.append(Paragraph(clean_text(part), styles['CustomBodyText']))
            
            else:
                elements.append(Paragraph(clean_text(part), styles['CustomBodyText']))
        
        elements.append(Spacer(1, 0.2 * inch))

    # Build PDF
    # We can't use the custom canvas class easily with SimpleDocTemplate without passing it to build
    # But SimpleDocTemplate.build accepts canvasmaker
    try:
        doc.build(elements, canvasmaker=TripTacticxTemplate)
    except Exception as e:
        print(f"PDF Build Error: {e}")
        # Fallback if canvasmaker fails
        doc.build(elements)

    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data

# Email sending function (kept as is)
def send_email_with_pdf(name, to_email, pdf_data):
    EMAIL_ADDRESS = os.environ.get('EMAIL_ADDRESS')  # Load from .env
    EMAIL_PASSWORD = os.environ.get('EMAIL_PASSWORD')

    if not EMAIL_ADDRESS or not EMAIL_PASSWORD:
        return False, "Email not configured (Secrets missing)", True

    msg = EmailMessage()
    msg['Subject'] = f"Your TripTacticx Travel Plan, {name}"
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = to_email
    msg.set_content(f"Hi {name},\n\nPlease find attached your personalized travel plan.\n\nSafe travels!\n\n- TripTacticx Team")

    msg.add_attachment(pdf_data, maintype='application', subtype='pdf', filename='TripTacticx_TravelPlan.pdf')

    try:
        # 10 second timeout to prevent worker hang
        with smtplib.SMTP_SSL('smtp.gmail.com', 465, timeout=10) as smtp:
            smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
            smtp.send_message(msg)
        return True, "Email sent successfully", False
    except Exception as e:
        print(f"Email sending failed: {e}")
        return False, str(e), False

# ================= AUTH ROUTES =================

@app.route('/signup', methods=['POST'])
def signup():
    data = request.json
    email = data.get('email')
    password = data.get('password')
    name = data.get('name')
    admin_secret = data.get('admin_secret')

    if not email or not password or not name:
        return jsonify({'error': 'Missing fields'}), 400

    if User.query.filter_by(email=email).first():
        return jsonify({'error': 'Email already exists'}), 400

    # Admin check: Either specific email OR correct secret key
    is_admin = False
    if email.lower() == 'triptacticx@gmail.com' or email.lower() == os.environ.get('ADMIN_EMAIL', '').lower():
        is_admin = True
    elif admin_secret == 'admin123': # Simple secret key for demo
        is_admin = True

    new_user = User(
        email=email,
        name=name,
        password_hash=generate_password_hash(password),
        is_admin=is_admin
    )
    db.session.add(new_user)
    db.session.commit()

    return jsonify({'message': 'User created successfully', 'is_admin': is_admin}), 201

@app.route('/login', methods=['POST'])
def login():
    data = request.json
    email = data.get('email')
    password = data.get('password')

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password_hash, password):
        return jsonify({'error': 'Invalid credentials'}), 401

    login_user(user)
    return jsonify({
        'message': 'Logged in successfully',
        'user': {'email': user.email, 'name': user.name, 'is_admin': user.is_admin}
    })

@app.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()
    return jsonify({'message': 'Logged out successfully'})

@app.route('/check-auth', methods=['GET'])
def check_auth():
    if current_user.is_authenticated:
        return jsonify({
            'authenticated': True,
            'user': {'email': current_user.email, 'name': current_user.name, 'is_admin': current_user.is_admin}
        })
    return jsonify({'authenticated': False})

# ================= CORE APP ROUTES =================

@app.route('/plan-trip', methods=['POST'])
@login_required
def plan_trip():
    try:
        data = request.json
        if not data:
            return jsonify({'error': 'No data received.'}), 400
        
        name = data.get('name')
        email = data.get('email')
        destination = data.get('destination')
        # days_str = data.get('days') # REMOVED
        start_date_str = data.get('start_date')
        end_date_str = data.get('end_date')
        group_size_str = data.get('group_size')
        budget_input = data.get('budget')
        trip_type = data.get('trip_type')
        preferences = data.get('preferences', '')
        source_location = data.get('source_location')
        whatsapp_number = data.get('whatsapp_number')
        transport_mode = data.get('transport_mode', 'Flight')

        # Basic validations
        if not all([name, email, destination, start_date_str, end_date_str, group_size_str, budget_input, trip_type, source_location]):
            return jsonify({'error': 'Missing required fields'}), 400

        try:
            # Parse dates and calculate duration
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()
            
            if end_date < start_date:
                return jsonify({'error': 'End date must be after start date'}), 400
                
            days = (end_date - start_date).days + 1
            
            group_size = int(group_size_str)
            budget_str_cleaned = str(budget_input).replace("Rs", "").replace(",", "").strip()
            budget = float(budget_str_cleaned)
        except ValueError as ve:
             return jsonify({'error': f'Invalid format: {str(ve)}'}), 400

        # Run AI Agent
        summary, agent_outputs = run_multi_agent(
            destination=destination,
            days=days,
            group_size=group_size,
            budget=budget,
            trip_type=trip_type,
            preferences=preferences,
            source_location=source_location,
            transport_mode=transport_mode
        )
        
        # Save to DB
        new_trip = Trip(
            user_id=current_user.id,
            destination=destination,
            start_date=start_date,
            end_date=end_date,
            days=days,
            group_size=group_size,
            budget=budget,
            trip_type=trip_type,
            whatsapp_number=whatsapp_number,
            details_json=json.dumps(agent_outputs)
        )
        db.session.add(new_trip)
        db.session.commit()

        # Generate PDF & Email
        pdf_data = None
        pdf_error = None
        try:
            pdf_data = generate_pdf(summary, agent_outputs)
        except Exception as e:
            print(f"PDF Gen Error: {e}")
            pdf_error = str(e)

        email_sent = False
        email_error = None
        if pdf_data:
            success, msg, skipped = send_email_with_pdf(name, email, pdf_data)
            email_sent = success
            if not success:
               email_error = msg
        else:
            email_error = "PDF Generation Failed: " + (pdf_error if pdf_error else "Unknown Error")

        return jsonify({
            'summary': summary,
            'agent_outputs': agent_outputs,
            'email_sent': email_sent,
            'email_error': email_error,
            'whatsapp_sent': True if whatsapp_number else False, # return status
            'trip_id': new_trip.id
        })

    except Exception as e:
        import traceback
        print("Error:", traceback.format_exc())
        return jsonify({'error': str(e)}), 400

@app.route('/api/my-trips', methods=['GET'])
@login_required
def my_trips():
    trips = Trip.query.filter_by(user_id=current_user.id).order_by(Trip.created_at.desc()).all()
    return jsonify([{
        'id': t.id,
        'destination': t.destination,
        'days': t.days,
        'budget': t.budget,
        'created_at': t.created_at.strftime('%Y-%m-%d'),
        'details': json.loads(t.details_json) if t.details_json else {}
    } for t in trips])

# ================= ADMIN ROUTES =================

@app.route('/api/admin/users', methods=['GET'])
@login_required
def get_all_users():
    if not current_user.is_admin:
        return jsonify({'error': 'Unauthorized'}), 403
    users = User.query.all()
    return jsonify([{'id': u.id, 'name': u.name, 'email': u.email, 'is_admin': u.is_admin} for u in users])

@app.route('/api/admin/trips', methods=['GET'])
@login_required
def get_all_trips():
    if not current_user.is_admin:
        return jsonify({'error': 'Unauthorized'}), 403
    trips = Trip.query.order_by(Trip.created_at.desc()).all()
    return jsonify([{
        'id': t.id,
        'user_name': t.user.name,
        'user_email': t.user.email,
        'whatsapp_number': t.whatsapp_number,
        'destination': t.destination,
        'budget': t.budget,
        'created_at': t.created_at.strftime('%Y-%m-%d')
    } for t in trips])

@app.route('/api/chat', methods=['POST'])
def chat_with_compass():
    from groq import Groq
    
    data = request.json
    messages = data.get('messages', [])
    
    if not messages:
        return jsonify({'error': 'No messages provided'}), 400

    api_key = os.environ.get('GROQ_API_KEY')
    if not api_key:
        return jsonify({'error': 'Server config error: API Key missing'}), 500

    client = Groq(api_key=api_key)
    
    # System prompt to define persona
    system_prompt = {
        "role": "system",
        "content": (
            "You are 'Compass', a helpful and concise AI travel assistant for TripTacticx. "
            "Your goal is to help undecided travelers find the perfect destination in **India**."
            "Ask 1-2 short clarifying questions if needed (e.g., 'Do you prefer beaches or mountains?', 'Is this for relaxation or adventure?'). "
            "Once you have enough info, suggest 2-3 specific Indian destinations with a 1-sentence reason for each. "
            "Keep responses short (under 50 words) and friendly. Do not use complex formatting."
        )
    }
    
    # Prepend system prompt to conversation
    full_conversation = [system_prompt] + messages[-10:] # Keep context small

    try:
        chat_completion = client.chat.completions.create(
            messages=full_conversation,
            model="llama-3.3-70b-versatile", # or slightly faster/smaller model
        )
        reply = chat_completion.choices[0].message.content
        return jsonify({'reply': reply})
    except Exception as e:
        print(f"Chat Error: {e}")
        return jsonify({'error': 'Compass is having trouble connecting.'}), 500

@app.route('/api/recommend', methods=['POST'])
def recommend_destination():
    from groq import Groq
    
    data = request.json
    start_date = data.get('start_date')
    trip_type = data.get('trip_type', 'Leisure')
    
    if not start_date:
        return jsonify({'error': 'Please select a Start Date first.'}), 400

    api_key = os.environ.get('GROQ_API_KEY')
    if not api_key:
        return jsonify({'error': 'Server config error'}), 500
        
    client = Groq(api_key=api_key)
    
    # Prompt for top 5 recommendations
    prompt = (
        f"Suggest the top 5 distinct travel destinations in India for a trip starting on {start_date}."
        f"Consider the weather and season for that specific date. "
        f"The trip vibe is {trip_type}. "
        f"Return ONLY a JSON object with a key 'suggestions' which is a list of 5 objects. "
        f"Each object must have keys: 'destination' (just the city/place name) and 'reason' (very short 1 sentence explanation of weather/why). "
        f"Do not include any other text."
    )
    
    try:
        chat_completion = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="llama-3.3-70b-versatile",
            response_format={"type": "json_object"}
        )
        content = chat_completion.choices[0].message.content
        return jsonify(json.loads(content))
    except Exception as e:
        print(f"Recommend Error: {e}")
        return jsonify({'error': 'Could not fetch recommendation.'}), 500


# ================= API ROUTES =================

@app.route('/api/contact', methods=['POST'])
def submit_contact():
    data = request.json
    name = data.get('name')
    email = data.get('email')
    message = data.get('message')

    if not all([name, email, message]):
        return jsonify({'error': 'All fields are required'}), 400
    
    # Save to DB
    new_query = ContactQuery(name=name, email=email, message=message)
    db.session.add(new_query)
    db.session.commit()
    
    return jsonify({'message': 'Message received. We will contact you soon.'}), 201

@app.route('/api/admin/messages', methods=['GET'])
@login_required
def get_contact_messages():
    if not current_user.is_admin:
        return jsonify({'error': 'Unauthorized'}), 403
    
    messages = ContactQuery.query.order_by(ContactQuery.created_at.desc()).all()
    return jsonify([{
        'id': m.id,
        'name': m.name,
        'email': m.email,
        'message': m.message,
        'created_at': m.created_at.strftime('%Y-%m-%d %H:%M')
    } for m in messages])

# News Ticker API (Previous endpoint logic here)
@app.route('/api/news', methods=['GET'])
def get_travel_news():
    import requests
    
    # Try to get API key
    api_key = os.environ.get('NEWS_API_KEY')
    
    # Mock data for fallback (or if no key)
    mock_news = [
        {"title": "India's Tourism Sector Expected to Grow by 15% in 2026", "source": "Travel India", "url": "#"},
        {"title": "New Vande Bharat Trains Launched for Major Tourist Routes", "source": "Rail News", "url": "#"},
        {"title": "Goa Becomes Top Destination for Remote Workers this Season", "source": "Nomad Life", "url": "#"},
        {"title": "Kerala Tourism Wins Award for Responsible Travel Initiatives", "source": "World Travel Awards", "url": "#"},
        {"title": "Visa-Free Entry for Indians Announced by 3 More Countries", "source": "Global Visa", "url": "#"}
    ]

    if not api_key:
        return jsonify(mock_news)

    # If key exists, try to fetch real news
    try:
        url = f"https://newsapi.org/v2/everything?q=india+tourism+travel&sortBy=publishedAt&language=en&apiKey={api_key}"
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            data = response.json()
            articles = data.get('articles', [])
            news_items = []
            for art in articles[:8]: # Top 8 news
                news_items.append({
                    "title": art.get('title'),
                    "source": art.get('source', {}).get('name'),
                    "url": art.get('url')
                })
            return jsonify(news_items)
        else:
            return jsonify(mock_news) # Fallback on error
    except Exception as e:
        print(f"News API Error: {e}")
        return jsonify(mock_news)

# ================= STATIC ROUTES =================

@app.route("/")
def serve_index():
    return send_from_directory(app.static_folder, "index.html")

@app.route("/<path:path>")
def serve_static(path):
    return send_from_directory(app.static_folder, path)

if __name__ == '__main__':
    app.run(debug=True, port=5001)
